
env_id: 'CarRacing-v3'
seed: 42
device: 'cuda'               
torch_deterministic: True    
gym_logger_level: 40         
save_model: True

# --- Training Control ---
n_episodes: 1000             
max_steps_per_episode: 1000  
render_during_training: False
eval_frequency: 50
eval_epoch: 10

# --- DDPG Parameters ---
ddpg_params:
  gamma: 0.99                
  tau: 0.005                
  actor_lr: 0.0001           
  critic_lr: 0.001          

# --- Replay Buffer  ---
replay_buffer_params:                
  capacity: 131072          
  batch_size: 64           
  alpha: 0.6            
  beta_start: 0.4           
  beta_frames: 1000000       
  eps: 0.000001              

# --- Ornstein-Uhlenbeck process ---
ou_noise_params: 
  theta: 0.15                
  mu: 0.0                   
  sigma: 0.2          

# --- Preprocessing ---
preprocessing_params: 
  normalize_factor: 255.0   

# --- Plotting ---
plotting_params: 
  reward_plot_title: 'DDPG w/ PER on CarRacing-v3 (from YAML)'
  reward_plot_filename: 'ddpg_per_rewards_from_yaml.pdf'
