# Configuration for Simplified PPO for CarRacing-v3

# Experiment setup
seed: 1
torch_deterministic: True
cuda: True
env_id: "CarRacing-v3"

save_model: True # Enable/disable saving the final model
capture_video: True # Enable/disable video recording
video_frequency: 50 # Record a video every N iterations (e.g., 50)


frame_stack: 4

# Training parameters
total_timesteps: 500000
learning_rate: 0.0003 # 3e-4
num_envs: 8
num_steps: 1024
anneal_lr: True

# PPO specific parameters
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 32
update_epochs: 10
norm_adv: True
clip_coef: 0.2
clip_vloss: True
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: null # Use null for None in YAML
